version: '3.9'
services:
  backend:
    container_name: desafio_maxmilhas_backend
    build: ./backend
    ports:
      - 3001:3001
    platforms:
      - linux/amd64
    working_dir: /app-backend
    volumes:
      - ./backend:/app-backend
    depends_on:
      - db:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      - JWT_SECRET=jwt_secret
      - DB_HOST=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 40s
  db:
    image: mysql:8.0.21
    container_name: desafio_maxmilhas_db
    platforms:
      - linux/amd64
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
