version: '3.9'
services:
  backend:
    container_name: desafio_maxmilhas_backend
    build: ./backend
    ports:
      - 3001:3001
    working_dir: /app-backend
    volumes:
      - ./backend:/app-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_NAME=desafio_maxmilhas
      - DB_PORT=3306
      - PORT=3001
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 40s
  db:
    image: mysql:8.0.21
    container_name: desafio_maxmilhas_db
    ports:
      - 3002:3306
    volumes:
      - "./db/migration.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./db/seed.sql:/docker-entrypoint-initdb.d/2.sql"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
